//variable//
var t1 = document.getElementById("text1");
var t2 = document.getElementById("text2");
var t3 = document.getElementById("text3");
var t4 = document.getElementById("text4");

var t5 = document.getElementById("one");
var t6 = document.getElementById("two");
var t7 = document.getElementById("three");
var t8 = document.getElementById("four");
var t9 = document.getElementById("five");
var t10 = document.getElementById("six");

function clickRed() {
  document.getElementById("ghost").classList.add("translucent");
  document.getElementById("sky").classList.remove("translucent");
  document.getElementById("wolf").classList.remove("translucent");
  document.getElementById("castle").classList.remove("translucent");
  document.getElementById("Okay").classList.remove("invisible");
  t5.src = "images/chihiro.png";
  t6.src = "images/haku.jpeg";
  t7.src = "images/noface.png";
  t8.src = "images2/chihiroo.gif";
  t9.src = "images2/hakuu.gif";
  t10.src = "images2/nofaceee.gif";
  t1.innerText = "千と千尋の神隠し (Spirited Away)";
  t2.innerText = "千尋 (Chihiro)";
  t3.innerText = "ハク (Haku)";
  t4.innerText = "カオナシ (No face)";
  document.getElementById("movieName").classList.add("greyish");
  document.getElementById("rowrowrow").classList.add("orange");
  document.getElementById("rowYellow").classList.add("light-yellow");
  document.getElementById("rowOrange").classList.add("light-orange");
  document.getElementById("rowGreen").classList.add("light-green");
  document.getElementById("rowPink").classList.add("pink");
  document.getElementById("rowWhite").classList.add("white");
  document.getElementById("rowGrey").classList.add("light-grey");
  document.getElementById("rowYay").classList.add("white");
  document.getElementById("rowBlack").classList.add("black");
  document.getElementById("rowAbc").classList.add("light-yellow");
  document.getElementById("rowDef").classList.add("light-orange");
  document.getElementById("rowGhi").classList.add("light-green");
  document.getElementById("time").play();
  document.getElementById("finally").pause();
  document.getElementById("finally").currentTime = 0;
  document.getElementById("to").pause();
  document.getElementById("to").currentTime = 0;
  document.getElementById("finish").pause();
  document.getElementById("finish").currentTime = 0;
  document.getElementById("movieName").classList.remove("greyish");
  document.getElementById("movieName").classList.add("red");
  document.getElementById("movieName").classList.remove("dark-green");
  document.getElementById("movieName").classList.remove("bronze");
  document.getElementById("movieName").classList.remove("navy-blue");
}

function clickGreen() {
  document.getElementById("sky").classList.add("translucent");
  document.getElementById("ghost").classList.remove("translucent");
  document.getElementById("wolf").classList.remove("translucent");
  document.getElementById("castle").classList.remove("translucent");
  document.getElementById("Okay").classList.remove("invisible");
  t5.src = "images/sheeta.jpg";
  t6.src = "images/pazu.jpeg";
  t7.src = "images/robot.jpeg";
  t8.src = "images2/sheetaaaa.gif";
  t9.src = "images2/panoishi.gif";
  t10.src = "images2/robotflower.gif";
  t1.innerText = "天空の城ラピュタ (Castle in the Sky)";
  t2.innerText = "シータ (Sheeta)";
  t3.innerText = "パズー (Pazu)";
  t4.innerText = "ロボット兵 (Castle Robot)";
  document.getElementById("movieName").classList.add("greyish");
  document.getElementById("rowrowrow").classList.add("orange");
  document.getElementById("rowYellow").classList.add("light-yellow");
  document.getElementById("rowOrange").classList.add("light-orange");
  document.getElementById("rowGreen").classList.add("light-green");
  document.getElementById("rowPink").classList.add("pink");
  document.getElementById("rowWhite").classList.add("white");
  document.getElementById("rowGrey").classList.add("light-grey");
  document.getElementById("rowYay").classList.add("white");
  document.getElementById("rowBlack").classList.add("black");
  document.getElementById("rowAbc").classList.add("light-yellow");
  document.getElementById("rowDef").classList.add("light-orange");
  document.getElementById("rowGhi").classList.add("light-green");
  document.getElementById("finally").play();
  document.getElementById("time").pause();
  document.getElementById("time").currentTime = 0;
  document.getElementById("to").pause();
  document.getElementById("to").currentTime = 0;
  document.getElementById("finish").pause();
  document.getElementById("finish").currentTime = 0;
  document.getElementById("movieName").classList.remove("greyish");
  document.getElementById("movieName").classList.add("dark-green");
  document.getElementById("movieName").classList.remove("red");
  document.getElementById("movieName").classList.remove("bronze");
  document.getElementById("movieName").classList.remove("navy-blue");
}

function clickYellow() {
  document.getElementById("wolf").classList.add("translucent");
  document.getElementById("sky").classList.remove("translucent");
  document.getElementById("ghost").classList.remove("translucent");
  document.getElementById("castle").classList.remove("translucent");
  document.getElementById("Okay").classList.remove("invisible");
  t5.src = "images/ashitaka.jpg";
  t6.src = "images/san.jpeg";
  t7.src = "images/yakul.jpeg";
  t9.src = "images2/sanyes.gif";
  t10.src = "images2/forestyakul.gif";
  t1.innerText = "もののけ姫 (Princess Mononoke)";
  t2.innerText = " アシタカ (Ashitaka)";
  t3.innerText = "サン (San)";
  t4.innerText = "ヤックル (Yakul)";
  document.getElementById("movieName").classList.add("greyish");
  document.getElementById("rowrowrow").classList.add("orange");
  document.getElementById("rowYellow").classList.add("light-yellow");
  document.getElementById("rowOrange").classList.add("light-orange");
  document.getElementById("rowGreen").classList.add("light-green");
  document.getElementById("rowPink").classList.add("pink");
  document.getElementById("rowWhite").classList.add("white");
  document.getElementById("rowGrey").classList.add("light-grey");
  document.getElementById("rowYay").classList.add("white");
  document.getElementById("rowBlack").classList.add("black");
  document.getElementById("rowAbc").classList.add("light-yellow");
  document.getElementById("rowDef").classList.add("light-orange");
  document.getElementById("rowGhi").classList.add("light-green");
  document.getElementById("to").play();
  document.getElementById("finally").pause();
  document.getElementById("finally").currentTime = 0;
  document.getElementById("time").pause();
  document.getElementById("time").currentTime = 0;
  document.getElementById("finish").pause();
  document.getElementById("finish").currentTime = 0;
  document.getElementById("movieName").classList.remove("greyish");
  document.getElementById("movieName").classList.add("bronze");
  document.getElementById("movieName").classList.remove("red");
  document.getElementById("movieName").classList.remove("dark-green");
  document.getElementById("movieName").classList.remove("navy-blue");
}

function clickBlue() {
  document.getElementById("castle").classList.add("translucent");
  document.getElementById("sky").classList.remove("translucent");
  document.getElementById("wolf").classList.remove("translucent");
  document.getElementById("ghost").classList.remove("translucent");
  document.getElementById("Okay").classList.remove("invisible");
  t5.src = "images/sofie.jpg";
  t6.src = "images/howl.jpeg";
  t7.src = "images/calcifer.jpeg";
  t8.src = "images2/sofieyes.gif";
  t9.src = "images2/howlyes.gif";
  t10.src = "images2/calciferyes.gif";
  t1.innerText = "ハウルの動く城 (Howl's moving Castle)";
  t2.innerText = "ソフィー(Sofie)";
  t3.innerText = " ハウル (Howl)";
  t4.innerText = "カルシファー(Calcifer)";
  document.getElementById("movieName").classList.add("greyish");
  document.getElementById("rowrowrow").classList.add("orange");
  document.getElementById("rowYellow").classList.add("light-yellow");
  document.getElementById("rowOrange").classList.add("light-orange");
  document.getElementById("rowGreen").classList.add("light-green");
  document.getElementById("rowPink").classList.add("pink");
  document.getElementById("rowWhite").classList.add("white");
  document.getElementById("rowGrey").classList.add("light-grey");
  document.getElementById("rowYay").classList.add("white");
  document.getElementById("rowBlack").classList.add("black");
  document.getElementById("rowAbc").classList.add("light-yellow");
  document.getElementById("rowDef").classList.add("light-orange");
  document.getElementById("rowGhi").classList.add("light-green");
  document.getElementById("finish").play();
  document.getElementById("finally").pause();
  document.getElementById("finally").currentTime = 0;
  document.getElementById("time").pause();
  document.getElementById("time").currentTime = 0;
  document.getElementById("to").pause();
  document.getElementById("to").currentTime = 0;
  document.getElementById("movieName").classList.remove("greyish");
  document.getElementById("movieName").classList.add("navy-blue");
  document.getElementById("movieName").classList.remove("red");
  document.getElementById("movieName").classList.remove("dark-green");
  document.getElementById("movieName").classList.remove("bronze");
}

function resetAll() {
  document.getElementById("ghost").classList.remove("translucent");
  document.getElementById("sky").classList.remove("translucent");
  document.getElementById("wolf").classList.remove("translucent");
  document.getElementById("castle").classList.remove("translucent");
  t1.innerText = "";
  t2.innerText = "";
  t3.innerText = "";
  t4.innerText = "";
  t5.src = "";
  t6.src = "";
  t7.src = "";
  t8.src = "";
  t9.src = "";
  t10.src = "";
  document.getElementById("movieName").classList.remove("greyish");
  document.getElementById("rowrowrow").classList.remove("orange");
  document.getElementById("rowYellow").classList.remove("light-yellow");
  document.getElementById("rowOrange").classList.remove("light-orange");
  document.getElementById("rowGreen").classList.remove("light-green");
  document.getElementById("rowPink").classList.remove("pink");
  document.getElementById("rowWhite").classList.remove("white");
  document.getElementById("rowGrey").classList.remove("light-grey");
  document.getElementById("rowYay").classList.remove("white");
  document.getElementById("rowBlack").classList.remove("black");
  document.getElementById("rowAbc").classList.remove("light-yellow");
  document.getElementById("rowDef").classList.remove("light-orange");
  document.getElementById("rowGhi").classList.remove("light-green");
  document.getElementById("finally").pause();
  document.getElementById("finally").currentTime = 0;
  document.getElementById("time").pause();
  document.getElementById("time").currentTime = 0;
  document.getElementById("to").pause();
  document.getElementById("to").currentTime = 0;
  document.getElementById("finish").pause();
  document.getElementById("finish").currentTime = 0;
  document.getElementById("movieName").classList.remove("red");
  document.getElementById("movieName").classList.remove("dark-green");
  document.getElementById("movieName").classList.remove("bronze");
  document.getElementById("movieName").classList.remove("navy-blue");
}
